baseURL = "https://www.takuzen.me"
languageCode = "en-us"
title = "マクロス"
theme = "hugo-theme-cactus"
copyright = "呉" # cactus will use title if copyright is not set
disqusShortname = "wzr" # cactus will use site title if not set
# googleAnalytics = "UA-83047470-2"

[markup.goldmark.renderer]
unsafe= true

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true
  googleAnalyticsAsync = true # not required
  # mathjax = true  # not required

  # Home page settings
  description = "勉強中"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true
  postsOnHomePage = 5
  tagsOverview = true
  showProjectsList = true
  projectsUrl = "https://github.com/monkeyWzr"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  # dateFormat = "2006-01-02"

  # Post page settings
  show_updated = false

  [params.comments]
    enabled = true
    engine = "disqus" #

  [[params.social]]
    name = "github"
    link = "https://github.com/monkeyWzr"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/monkeywzr/"
  [[params.social]]
    name = "email"
    link = "monkeywzr@gmail.com"  # no need for "mailto:" at the start
